{% set name = "diagrams" %}
{% set version = "0.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47b77a0e4dac926a095ff2ae4dd4ec1a192be781799befc660a8f5ce6ea1052f
  patches:
    - 0001-Set-packages.patch

build:
  number: 0
  noarch: python
  script:
    - $PYTHON -m pip install . -vv
    - cp -r $SRC_DIR/resources $SP_DIR/resources
requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }}
    - jinja2 >=2.10,<4.0
    - python-graphviz >=0.13.2,<0.21.0
    - typed-ast >=1.5.5,<2.0.0

test:
  imports:
    - diagrams
    - diagrams.alibabacloud
    - diagrams.aws
    - diagrams.azure
    - diagrams.base
    - diagrams.custom
    - diagrams.gcp
    - diagrams.k8s
    - diagrams.oci
    - diagrams.onprem
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://diagrams.mingrammer.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Diagram as Code
  doc_url: https://diagrams.mingrammer.com/
  dev_url: https://github.com/mingrammer/diagrams

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
    - dhirschfeld
    - dbast
